In [1039]:
from sudoku import Sudoku
# Initializes a Sudoku puzzle with 3 x 3 sub-grid and
# generates a puzzle with half of the cells empty
puzzle = Sudoku(3).difficulty(0.5)
print(puzzle.board)
puzzle.show()
p =puzzle.solve()
p.show()

[[None, None, None, None, 8, None, None, 3, 7], [None, 7, None, 5, 1, None, None, None, None], [1, 8, 9, None, 7, 3, None, 4, 5], [7, None, 8, 9, None, 4, None, 2, 3], [3, 9, None, 8, 2, 6, 5, None, 1], [None, None, 5, 1, None, 7, None, None, 4], [9, 4, 1, 3, 6, None, None, None, None], [None, 6, None, None, None, None, 3, None, 9], [5, None, None, 2, None, None, None, 8, None]]
+-------+-------+-------+
|       |   8   |   3 7 |
|   7   | 5 1   |       |
| 1 8 9 |   7 3 |   4 5 |
+-------+-------+-------+
| 7   8 | 9   4 |   2 3 |
| 3 9   | 8 2 6 | 5   1 |
|     5 | 1   7 |     4 |
+-------+-------+-------+
| 9 4 1 | 3 6   |       |
|   6   |       | 3   9 |
| 5     | 2     |   8   |
+-------+-------+-------+

+-------+-------+-------+
| 2 5 6 | 4 8 9 | 1 3 7 |
| 4 7 3 | 5 1 2 | 9 6 8 |
| 1 8 9 | 6 7 3 | 2 4 5 |
+-------+-------+-------+
| 7 1 8 | 9 5 4 | 6 2 3 |
| 3 9 4 | 8 2 6 | 5 7 1 |
| 6 2 5 | 1 3 7 | 8 9 4 |
+-------+-------+-------+
| 9 4 1 | 3 6 8 | 7 5 2 |
| 8 6 2 | 7 4 5 | 3

In [1040]:
type(puzzle.board[0][3])

NoneType

In [1041]:
#Cleaning up the board None -> 0
grid = puzzle.board
print(grid)

for i in range(0,len(grid)):
    for j in range(0,len(grid[i])):
        if grid[i][j]==None:
            grid[i][j]=0
            

print("Clean -----------------------------")            
print(grid)

[[None, None, None, None, 8, None, None, 3, 7], [None, 7, None, 5, 1, None, None, None, None], [1, 8, 9, None, 7, 3, None, 4, 5], [7, None, 8, 9, None, 4, None, 2, 3], [3, 9, None, 8, 2, 6, 5, None, 1], [None, None, 5, 1, None, 7, None, None, 4], [9, 4, 1, 3, 6, None, None, None, None], [None, 6, None, None, None, None, 3, None, 9], [5, None, None, 2, None, None, None, 8, None]]
Clean -----------------------------
[[0, 0, 0, 0, 8, 0, 0, 3, 7], [0, 7, 0, 5, 1, 0, 0, 0, 0], [1, 8, 9, 0, 7, 3, 0, 4, 5], [7, 0, 8, 9, 0, 4, 0, 2, 3], [3, 9, 0, 8, 2, 6, 5, 0, 1], [0, 0, 5, 1, 0, 7, 0, 0, 4], [9, 4, 1, 3, 6, 0, 0, 0, 0], [0, 6, 0, 0, 0, 0, 3, 0, 9], [5, 0, 0, 2, 0, 0, 0, 8, 0]]


In [1042]:
#To print in a readable format
import numpy as np
print(np.matrix(grid))

[[0 0 0 0 8 0 0 3 7]
 [0 7 0 5 1 0 0 0 0]
 [1 8 9 0 7 3 0 4 5]
 [7 0 8 9 0 4 0 2 3]
 [3 9 0 8 2 6 5 0 1]
 [0 0 5 1 0 7 0 0 4]
 [9 4 1 3 6 0 0 0 0]
 [0 6 0 0 0 0 3 0 9]
 [5 0 0 2 0 0 0 8 0]]


In [1043]:
#defining grid manually
#grid = [[0, 0, 0, 0, 0, 8, 0, 6, 0], 
#        [0, 1, 5, 0, 0, 0, 0, 2, 0], 
#        [0, 0, 5, 2, 0, 7, 4, 8, 0], 
#        [3, 5, 7, 0, 2, 0, 6, 0, 1], 
#        [0, 9, 0, 0, 0, 0, 0, 3, 0], 
#        [8, 1, 0, 6, 0, 0, 0, 0, 0], 
#        [5, 0, 1, 0, 0, 0, 0, 2, 4], 
#        [4, 7, 3, 0, 0, 2, 0, 0, 5], 
#        [0, 6, 0, 5, 0, 1, 8, 0, 0]]

In [1044]:
def isnumpossible(x,y,n):
    global grid
    for i in range(0,len(grid)):
        if(n==grid[x][i]):
            #print("1st")
            return False
    for i in range(0,len(grid[y])):
        if(n==grid[i][y]):
            #print("2nd")
            return False
    l=(x//3)*3
    m=(y//3)*3
    for i in range(m,m+3):
        for j in range(l,l+3):
            #print("Checking",i,j)
            if(n==grid[j][i]):
                #print(i,j,n)
                #print("3rd")
                return False
    return True

In [1045]:
isnumpossible(0,6,9)

True

In [1046]:
def solved():
    global grid
    for i in range(0,len(grid)):
        for j in range(0,len(grid)):
            if(grid[i][j]==0):
                return False
    return True

In [1047]:
def solver():
    global grid
    #global res_grid
    #print(np.matrix(grid))
    for i in range(0,len(grid)):
        #print(i)
        for j in range(0,len(grid[i])):
            #print(i)
            #print("---CHECKING if ",i,j, "is zero")
            #if(i==(len(grid)-1) and j==(len(grid)-1)):
            #    if(grid[i][j]!=0):
            #        print("STOPPINGGG")
            #        return
            if(grid[i][j]==0):
                #print("next zero at",i,j,grid[i][j])
                for x in range(1,10):
                    #print("-------------Passed: ",i,j,x)
                    if(isnumpossible(i,j,x)):
                        #print("-------------Qualified: ",i,j,x)
                        grid[i][j] = x
                        #print(len(grid)-1)
                        #if(i==(len(grid)-1) and j==(len(grid)-1)):
                        #    print(np.matrix(grid))
                        #    print("LAST")
                        #    return
                        #print("-------------")
                        #print(np.matrix(grid))
                        #if(i==8 and j==8):
                        #    res_grid = grid
                        solver()
                        grid[i][j]=0
                        #print("------Setting ",i,j,"To ZERO")
                return
    print(np.matrix(grid))
    #Comment the below return if multiple solutions needed
    return

In [1048]:
solver()

[[2 5 6 4 8 9 1 3 7]
 [4 7 3 5 1 2 9 6 8]
 [1 8 9 6 7 3 2 4 5]
 [7 1 8 9 5 4 6 2 3]
 [3 9 4 8 2 6 5 7 1]
 [6 2 5 1 3 7 8 9 4]
 [9 4 1 3 6 8 7 5 2]
 [8 6 2 7 4 5 3 1 9]
 [5 3 7 2 9 1 4 8 6]]
